name: PowerSuperAntiProxy
main: com.mrpowergamerbr.powersuperantiproxy.PowerSuperAntiProxy
version: 1.0.0
softdepend: [ProtocolLib]
commands:
   powerantiproxy:
      description: PowerAntiProxy
      usage: /<command>